/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunargrupo4.vistas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import vacunargrupo4.control.Conexion;
import vacunargrupo4.control.LabData;
import vacunargrupo4.modelos.Laboratorio;
import static vacunargrupo4.vistas.ViewRegistroPersona.validarString;



/**
 *
 * @author Maxi
 */
public class ViewVacuna extends javax.swing.JInternalFrame {

    private Border border;
    private Conexion conexion;
    private DefaultTableModel modelo;
    private LabData ld;
    private ArrayList <Laboratorio> laboratorios;
    
    public ViewVacuna(Conexion conexion) {
        this.conexion=conexion;
        initComponents();
        border = new LineBorder(Color.getHSBColor(0, 87, 100), 3, true);
        modelo = new DefaultTableModel();
        ld = new LabData(conexion);
        laboratorios = (ArrayList<Laboratorio>) ld.obtenerLaboratorios();
        cabeceraTabla();
        cargaDatosLab();       
    }
    
    
    public void cargaDatosLab(){
        borrarFilasTabla();
        for (Laboratorio c:laboratorios){
            modelo.addRow(new Object[]{c.getId(),c.getNombre(),c.getPaisOrigen(),c.getDireccion()});       
        }
    }

    public void cabeceraTabla(){
        ArrayList<Object> columns= new ArrayList();
        columns.add("ID");
        columns.add("Nombre");
        columns.add("Pais");
        columns.add("Direccion");
        for (Object it:columns){
            modelo.addColumn(it);
        }
        tLab.setModel(modelo);
    }

    public void borrarFilasTabla(){
        int b= modelo.getRowCount()-1;
        for(int i = b;i>=0;i--){
            modelo.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tLab = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtPais = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jbAdd = new javax.swing.JButton();
        jtBorrar = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setClosable(true);
        setIconifiable(true);

        jTabbedPane1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(150, 150));

        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jTabbedPane1.addTab("Vacunas", jToolBar1);

        jToolBar2.setRollover(true);

        tLab.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        tLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tLab.setFillsViewportHeight(true);
        tLab.setPreferredSize(new java.awt.Dimension(305, 85));
        jScrollPane1.setViewportView(tLab);

        jToolBar2.add(jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel2.setText("Pais");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel3.setText("Direccion");

        jtNombre.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N

        jtPais.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N

        jtDireccion.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N

        jbAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        jbAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jtBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jtBorrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNombre)
                            .addComponent(jtPais)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jtBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtDireccion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jbAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel1);

        jTabbedPane1.addTab("Laboratorios", jToolBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed

        LabData lb = new LabData(conexion);
        Laboratorio lab;
        
            try{
                String nombre = jtNombre.getText();
                if (nombre.isEmpty()){
                    JOptionPane.showMessageDialog(jMenu1, "Debe completar el Nombre");
                    jtNombre.requestFocus();
                    jtNombre.setBorder(border);
                }else{
                    String pais = jtPais.getText();
                    if (pais.isEmpty()){
                    JOptionPane.showMessageDialog(jMenu1, "Debe completar el Pais");
                    jtPais.requestFocus();
                    jtPais.setBorder(border);}
                    else if (!validarString(pais)){
                            JOptionPane.showMessageDialog(this, "Pais no puede contener numeros");
                            jtPais.requestFocus();
                            jtPais.setBorder(border);
                    }else{
                        String direccion = jtDireccion.getText();
                        if (direccion.isEmpty()){
                        JOptionPane.showMessageDialog(jMenu1, "Debe completar Direccion");
                        jtDireccion.requestFocus();
                        jtDireccion.setBorder(border);
                        }   else{
                                lab = new Laboratorio(nombre,direccion,pais);
                                lb.registrarLaboratorio(lab);
                                JOptionPane.showMessageDialog(jMenu1, "Laboratorio Agregado");
                                this.cargaDatosLab();
                            }   
                    }
                }
            }catch (NullPointerException e){
                JOptionPane.showMessageDialog(jMenu1, "Error en carga de datos");
                jtNombre.requestFocus();
                jtNombre.setBorder(border);
            }
            
    }//GEN-LAST:event_jbAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jtBorrar;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPais;
    private javax.swing.JTable tLab;
    // End of variables declaration//GEN-END:variables
}
